### ISSUE TITLE
node binding fails 403 forbidden when using node 7 with travis CI

### ISSUE THREAD

**Issue by MattMcFarland** [nodegit/nodegit#1161]
```
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v51-linux-x64.tar.gz 
```

config:
```
language: node_js
node_js:
  - '6'
  - '7'
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
```

You can see the whole log output here:
https://travis-ci.org/trainyard/choo-cli/jobs/177217273
