### ISSUE TITLE
nodegit and Github Actions. Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by claudiobizzotto** [nodegit/nodegit#1777]
## System information
  - node version: v12.18.1
  - npm version: 6.14.5
  - OS/version/architecture:  Docker container running Ubuntu 18.04 (Linux 5.3.0-1031-azure)
  - Applicable nodegit version: ^0.26.5
  - process.features.debug: false

I'm trying to use nodegit on a Github Actions job and getting this error:

```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
Require stack:
- /home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.973 (/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js:29823:33)
    at __webpack_require__ (/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js:24:31)
    at Object.634 (/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js:9708:12)
    at __webpack_require__ (/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js:24:31)
    at Object.809 (/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js:29191:13)
    at __webpack_require__ (/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js:24:31) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/xxxxxxxxxx/xxxxxxxxxx/dist/index.js' ]
}
```

I use `ncc` to package everything into a `dist/index.js` file, but I'm not sure that has anything to do with this. Even if I do an `npm install nodegit` as a separate step in the job (outside of `package.js`), still then Node can't find the required shared library (`nodegit.node`).

**Comment by claudiobizzotto** [comment]
It looks like the problem was indeed with how I expected things to work with `npm` and `ncc`... I've ditched `ncc` to install things from a regular `npm install` and things are working now. For reference:

```
jobs:
  test-nodegit:
    runs-on: ubuntu-20.04
    name: Test nodegit
    steps:
      - name: Check out current repo
        uses: actions/checkout@v2
      - name: Install NodeJS packages
        run: npm install
      - name: Test nodegit
        run: node -e "console.log(require('nodegit'));"
```
