### ISSUE TITLE
Failed to fetch from s3

### ISSUE THREAD

**Issue by whitneyit** [nodegit/nodegit#736]
After much fighting with travis, I finally got nodegit to run on a linux box using `nodegit@0.5.0`. The notable parts of my `.travis.yml` file are

```yml
sudo: false
language: node_js
node_js:
  - '0.12'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
      - libc6-dev

before_install:
  - export CC=/usr/bin/gcc-4.9;
  - export CXX=/usr/bin/g++-4.9;
```

That setup however yields the following [log](http://pastebin.com/CLtHBz6M). It all works but the `apt-get` stuff and the rebuild of nodegit added more than 10 minutes to my builds. Previously I was just using an `osx` box but that doesn't suit my use cases any more.

Is there somthing that I can help with to generate an s3 image that won't keep causing these downloads and builds?

Cheers
